# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/zedboard_hdmi_display.xdc

# Block Designs: bd/tutorial/tutorial.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tutorial || ORIG_REF_NAME==tutorial}]

# IP: bd/tutorial/ip/tutorial_processing_system7_0_0/tutorial_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tutorial_processing_system7_0_0 || ORIG_REF_NAME==tutorial_processing_system7_0_0}]

# IP: bd/tutorial/ip/tutorial_axi_iic_0_0/tutorial_axi_iic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tutorial_axi_iic_0_0 || ORIG_REF_NAME==tutorial_axi_iic_0_0}]

# IP: bd/tutorial/ip/tutorial_processing_system7_0_axi_periph_0/tutorial_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tutorial_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==tutorial_processing_system7_0_axi_periph_0}]

# IP: bd/tutorial/ip/tutorial_rst_processing_system7_0_100M_0/tutorial_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tutorial_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==tutorial_rst_processing_system7_0_100M_0}]

# IP: bd/tutorial/ip/tutorial_clk_wiz_0_0/tutorial_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tutorial_clk_wiz_0_0 || ORIG_REF_NAME==tutorial_clk_wiz_0_0}]

# IP: bd/tutorial/ip/tutorial_axi_mem_intercon_1/tutorial_axi_mem_intercon_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tutorial_axi_mem_intercon_1 || ORIG_REF_NAME==tutorial_axi_mem_intercon_1}]

# IP: bd/tutorial/ip/tutorial_axi_vdma_0_0/tutorial_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tutorial_axi_vdma_0_0 || ORIG_REF_NAME==tutorial_axi_vdma_0_0}]

# IP: bd/tutorial/ip/tutorial_axis_subset_converter_0_0/tutorial_axis_subset_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tutorial_axis_subset_converter_0_0 || ORIG_REF_NAME==tutorial_axis_subset_converter_0_0}]

# IP: bd/tutorial/ip/tutorial_gnd_0/tutorial_gnd_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tutorial_gnd_0 || ORIG_REF_NAME==tutorial_gnd_0}]

# IP: bd/tutorial/ip/tutorial_proc_sys_reset_1/tutorial_proc_sys_reset_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tutorial_proc_sys_reset_1 || ORIG_REF_NAME==tutorial_proc_sys_reset_1}]

# IP: bd/tutorial/ip/tutorial_v_axi4s_vid_out_0_0/tutorial_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tutorial_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==tutorial_v_axi4s_vid_out_0_0}]

# IP: bd/tutorial/ip/tutorial_v_rgb2ycrcb_0_0/tutorial_v_rgb2ycrcb_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tutorial_v_rgb2ycrcb_0_0 || ORIG_REF_NAME==tutorial_v_rgb2ycrcb_0_0}]

# IP: bd/tutorial/ip/tutorial_v_tc_0_0/tutorial_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tutorial_v_tc_0_0 || ORIG_REF_NAME==tutorial_v_tc_0_0}]

# IP: bd/tutorial/ip/tutorial_vcc_1/tutorial_vcc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tutorial_vcc_1 || ORIG_REF_NAME==tutorial_vcc_1}]

# IP: bd/tutorial/ip/tutorial_zed_hdmi_out_0_0/tutorial_zed_hdmi_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tutorial_zed_hdmi_out_0_0 || ORIG_REF_NAME==tutorial_zed_hdmi_out_0_0}]

# IP: bd/tutorial/ip/tutorial_xbar_2/tutorial_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tutorial_xbar_2 || ORIG_REF_NAME==tutorial_xbar_2}]

# IP: bd/tutorial/ip/tutorial_v_cresample_1_1/tutorial_v_cresample_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tutorial_v_cresample_1_1 || ORIG_REF_NAME==tutorial_v_cresample_1_1}]

# IP: bd/tutorial/ip/tutorial_auto_pc_11/tutorial_auto_pc_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tutorial_auto_pc_11 || ORIG_REF_NAME==tutorial_auto_pc_11}]

# IP: bd/tutorial/ip/tutorial_auto_pc_12/tutorial_auto_pc_12.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tutorial_auto_pc_12 || ORIG_REF_NAME==tutorial_auto_pc_12}]

# XDC: bd/tutorial/ip/tutorial_processing_system7_0_0/tutorial_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==tutorial_processing_system7_0_0 || ORIG_REF_NAME==tutorial_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/tutorial/ip/tutorial_axi_iic_0_0/tutorial_axi_iic_0_0_ooc.xdc

# XDC: bd/tutorial/ip/tutorial_axi_iic_0_0/tutorial_axi_iic_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==tutorial_axi_iic_0_0 || ORIG_REF_NAME==tutorial_axi_iic_0_0}] {/U0 }]/U0 ]]

# XDC: bd/tutorial/ip/tutorial_rst_processing_system7_0_100M_0/tutorial_rst_processing_system7_0_100M_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==tutorial_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==tutorial_rst_processing_system7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/tutorial/ip/tutorial_rst_processing_system7_0_100M_0/tutorial_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/tutorial/ip/tutorial_rst_processing_system7_0_100M_0/tutorial_rst_processing_system7_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==tutorial_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==tutorial_rst_processing_system7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/tutorial/ip/tutorial_clk_wiz_0_0/tutorial_clk_wiz_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==tutorial_clk_wiz_0_0 || ORIG_REF_NAME==tutorial_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/tutorial/ip/tutorial_clk_wiz_0_0/tutorial_clk_wiz_0_0_OOC.xdc

# XDC: bd/tutorial/ip/tutorial_clk_wiz_0_0/tutorial_clk_wiz_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==tutorial_clk_wiz_0_0 || ORIG_REF_NAME==tutorial_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/tutorial/ip/tutorial_axi_vdma_0_0/tutorial_axi_vdma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==tutorial_axi_vdma_0_0 || ORIG_REF_NAME==tutorial_axi_vdma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/tutorial/ip/tutorial_axi_vdma_0_0/tutorial_axi_vdma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==tutorial_axi_vdma_0_0 || ORIG_REF_NAME==tutorial_axi_vdma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/tutorial/ip/tutorial_axi_vdma_0_0/tutorial_axi_vdma_0_0_ooc.xdc

# XDC: bd/tutorial/ip/tutorial_axis_subset_converter_0_0/tutorial_axis_subset_converter_0_0_ooc.xdc

# XDC: bd/tutorial/ip/tutorial_proc_sys_reset_1/tutorial_proc_sys_reset_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==tutorial_proc_sys_reset_1 || ORIG_REF_NAME==tutorial_proc_sys_reset_1}] {/U0 }]/U0 ]]

# XDC: bd/tutorial/ip/tutorial_proc_sys_reset_1/tutorial_proc_sys_reset_1_ooc.xdc

# XDC: bd/tutorial/ip/tutorial_proc_sys_reset_1/tutorial_proc_sys_reset_1_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==tutorial_proc_sys_reset_1 || ORIG_REF_NAME==tutorial_proc_sys_reset_1}] {/U0 }]/U0 ]]

# XDC: bd/tutorial/ip/tutorial_v_axi4s_vid_out_0_0/tutorial_v_axi4s_vid_out_0_0_ooc.xdc

# XDC: bd/tutorial/ip/tutorial_v_axi4s_vid_out_0_0/tutorial_v_axi4s_vid_out_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==tutorial_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==tutorial_v_axi4s_vid_out_0_0}] {/inst }]/inst ]]

# XDC: bd/tutorial/ip/tutorial_v_rgb2ycrcb_0_0/tutorial_v_rgb2ycrcb_0_0_ooc.xdc

# XDC: bd/tutorial/ip/tutorial_v_rgb2ycrcb_0_0/tutorial_v_rgb2ycrcb_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==tutorial_v_rgb2ycrcb_0_0 || ORIG_REF_NAME==tutorial_v_rgb2ycrcb_0_0}] {/U0 }]/U0 ]]

# XDC: bd/tutorial/ip/tutorial_v_tc_0_0/tutorial_v_tc_0_0_ooc.xdc

# XDC: bd/tutorial/ip/tutorial_v_tc_0_0/tutorial_v_tc_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==tutorial_v_tc_0_0 || ORIG_REF_NAME==tutorial_v_tc_0_0}] {/U0 }]/U0 ]]

# XDC: bd/tutorial/ip/tutorial_xbar_2/tutorial_xbar_2_ooc.xdc

# XDC: bd/tutorial/ip/tutorial_v_cresample_1_1/tutorial_v_cresample_1_1_ooc.xdc

# XDC: bd/tutorial/ip/tutorial_v_cresample_1_1/tutorial_v_cresample_1_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==tutorial_v_cresample_1_1 || ORIG_REF_NAME==tutorial_v_cresample_1_1}] {/U0 }]/U0 ]]

# XDC: bd/tutorial/ip/tutorial_auto_pc_11/tutorial_auto_pc_11_ooc.xdc

# XDC: bd/tutorial/ip/tutorial_auto_pc_12/tutorial_auto_pc_12_ooc.xdc

# XDC: bd/tutorial/tutorial_ooc.xdc
