# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1
set_property target_language Verilog [current_project]
set_property board em.avnet.com:zynq:zed:d [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property ip_repo_paths /home/xyin/Embedded_System_Lab/Lab2_2/Repository [current_fileset]

add_files /home/xyin/Embedded_System_Lab/Lab2_2/Lab2_2.srcs/sources_1/bd/tutorial/tutorial.bd
set_property used_in_implementation false [get_files -all /home/xyin/Embedded_System_Lab/Lab2_2/Lab2_2.srcs/sources_1/bd/tutorial/ip/tutorial_processing_system7_0_0/tutorial_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/xyin/Embedded_System_Lab/Lab2_2/Lab2_2.srcs/sources_1/bd/tutorial/ip/tutorial_axi_iic_0_0/tutorial_axi_iic_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xyin/Embedded_System_Lab/Lab2_2/Lab2_2.srcs/sources_1/bd/tutorial/ip/tutorial_axi_iic_0_0/tutorial_axi_iic_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/xyin/Embedded_System_Lab/Lab2_2/Lab2_2.srcs/sources_1/bd/tutorial/ip/tutorial_rst_processing_system7_0_100M_0/tutorial_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/xyin/Embedded_System_Lab/Lab2_2/Lab2_2.srcs/sources_1/bd/tutorial/ip/tutorial_rst_processing_system7_0_100M_0/tutorial_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xyin/Embedded_System_Lab/Lab2_2/Lab2_2.srcs/sources_1/bd/tutorial/ip/tutorial_rst_processing_system7_0_100M_0/tutorial_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/xyin/Embedded_System_Lab/Lab2_2/Lab2_2.srcs/sources_1/bd/tutorial/ip/tutorial_clk_wiz_0_0/tutorial_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/xyin/Embedded_System_Lab/Lab2_2/Lab2_2.srcs/sources_1/bd/tutorial/ip/tutorial_clk_wiz_0_0/tutorial_clk_wiz_0_0_OOC.xdc]
set_property used_in_implementation false [get_files -all /home/xyin/Embedded_System_Lab/Lab2_2/Lab2_2.srcs/sources_1/bd/tutorial/ip/tutorial_clk_wiz_0_0/tutorial_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/xyin/Embedded_System_Lab/Lab2_2/Lab2_2.srcs/sources_1/bd/tutorial/ip/tutorial_axi_vdma_0_0/tutorial_axi_vdma_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/xyin/Embedded_System_Lab/Lab2_2/Lab2_2.srcs/sources_1/bd/tutorial/ip/tutorial_axi_vdma_0_0/tutorial_axi_vdma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/xyin/Embedded_System_Lab/Lab2_2/Lab2_2.srcs/sources_1/bd/tutorial/ip/tutorial_axi_vdma_0_0/tutorial_axi_vdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xyin/Embedded_System_Lab/Lab2_2/Lab2_2.srcs/sources_1/bd/tutorial/ip/tutorial_axis_subset_converter_0_0/tutorial_axis_subset_converter_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xyin/Embedded_System_Lab/Lab2_2/Lab2_2.srcs/sources_1/bd/tutorial/ip/tutorial_proc_sys_reset_1/tutorial_proc_sys_reset_1.xdc]
set_property used_in_implementation false [get_files -all /home/xyin/Embedded_System_Lab/Lab2_2/Lab2_2.srcs/sources_1/bd/tutorial/ip/tutorial_proc_sys_reset_1/tutorial_proc_sys_reset_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xyin/Embedded_System_Lab/Lab2_2/Lab2_2.srcs/sources_1/bd/tutorial/ip/tutorial_proc_sys_reset_1/tutorial_proc_sys_reset_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/xyin/Embedded_System_Lab/Lab2_2/Lab2_2.srcs/sources_1/bd/tutorial/ip/tutorial_v_axi4s_vid_out_0_0/tutorial_v_axi4s_vid_out_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xyin/Embedded_System_Lab/Lab2_2/Lab2_2.srcs/sources_1/bd/tutorial/ip/tutorial_v_axi4s_vid_out_0_0/tutorial_v_axi4s_vid_out_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/xyin/Embedded_System_Lab/Lab2_2/Lab2_2.srcs/sources_1/bd/tutorial/ip/tutorial_v_rgb2ycrcb_0_0/tutorial_v_rgb2ycrcb_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xyin/Embedded_System_Lab/Lab2_2/Lab2_2.srcs/sources_1/bd/tutorial/ip/tutorial_v_rgb2ycrcb_0_0/tutorial_v_rgb2ycrcb_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/xyin/Embedded_System_Lab/Lab2_2/Lab2_2.srcs/sources_1/bd/tutorial/ip/tutorial_v_tc_0_0/tutorial_v_tc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xyin/Embedded_System_Lab/Lab2_2/Lab2_2.srcs/sources_1/bd/tutorial/ip/tutorial_v_tc_0_0/tutorial_v_tc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/xyin/Embedded_System_Lab/Lab2_2/Lab2_2.srcs/sources_1/bd/tutorial/ip/tutorial_xbar_2/tutorial_xbar_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xyin/Embedded_System_Lab/Lab2_2/Lab2_2.srcs/sources_1/bd/tutorial/ip/tutorial_v_cresample_1_1/tutorial_v_cresample_1_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xyin/Embedded_System_Lab/Lab2_2/Lab2_2.srcs/sources_1/bd/tutorial/ip/tutorial_v_cresample_1_1/tutorial_v_cresample_1_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/xyin/Embedded_System_Lab/Lab2_2/Lab2_2.srcs/sources_1/bd/tutorial/ip/tutorial_auto_pc_11/tutorial_auto_pc_11_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xyin/Embedded_System_Lab/Lab2_2/Lab2_2.srcs/sources_1/bd/tutorial/ip/tutorial_auto_pc_12/tutorial_auto_pc_12_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xyin/Embedded_System_Lab/Lab2_2/Lab2_2.srcs/sources_1/bd/tutorial/tutorial_ooc.xdc]
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files /home/xyin/Embedded_System_Lab/Lab2_2/Lab2_2.srcs/sources_1/bd/tutorial/tutorial.bd]

read_verilog /home/xyin/Embedded_System_Lab/Lab2_2/Lab2_2.srcs/sources_1/bd/tutorial/hdl/tutorial_wrapper.v
read_xdc /home/xyin/Embedded_System_Lab/Lab2_2/Lab2_2.srcs/constrs_1/imports/constraints/zedboard_hdmi_display.xdc
set_property used_in_implementation false [get_files /home/xyin/Embedded_System_Lab/Lab2_2/Lab2_2.srcs/constrs_1/imports/constraints/zedboard_hdmi_display.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/xyin/Embedded_System_Lab/Lab2_2/Lab2_2.data/wt [current_project]
set_property parent.project_dir /home/xyin/Embedded_System_Lab/Lab2_2 [current_project]
synth_design -top tutorial_wrapper -part xc7z020clg484-1
write_checkpoint tutorial_wrapper.dcp
report_utilization -file tutorial_wrapper_utilization_synth.rpt -pb tutorial_wrapper_utilization_synth.pb
