# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1_2_2/design_1_2_2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_2_2 || ORIG_REF_NAME==design_1_2_2}]

# IP: bd/design_1_2_2/ip/design_1_2_2_processing_system7_0_0/design_1_2_2_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_2_2_processing_system7_0_0 || ORIG_REF_NAME==design_1_2_2_processing_system7_0_0}]

# XDC: bd/design_1_2_2/ip/design_1_2_2_processing_system7_0_0/design_1_2_2_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_2_2_processing_system7_0_0 || ORIG_REF_NAME==design_1_2_2_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/design_1_2_2/design_1_2_2_ooc.xdc
