#
# (C) Copyright 2007-2008 Michal Simek
#
# Michal SIMEK <monstr@monstr.eu>
#
# CAUTION: This file is automatically generated by libgen.
# Version: Xilinx EDK 2013.4 EDK_2013.4.20131205
# Generate by U-BOOT v4.00.c
# Project description at http://www.monstr.eu/uboot/
#


TEXT_BASE = 0x1fc00000
CONFIG_SYS_TEXT_BASE = 0x1fc00000
