/*
 * (C) Copyright 2007-2008 Michal Simek
 *
 * Michal SIMEK <monstr@monstr.eu>
 *
 * CAUTION: This file is automatically generated by libgen.
 * Version: Xilinx EDK 2013.4 EDK_2013.4.20131205
 * Generate by U-BOOT v4.00.c
 * Project description at http://www.monstr.eu/uboot/
 */

#define XILINX_BOARD_NAME	"."

/* ARM is ps7_cortexa9_0 */
#define XPAR_CPU_CORTEXA9_CORE_CLOCK_FREQ_HZ	666666687

/* Interrupt controller is ps7_scugic_0 */
#define XILINX_PS7_INTC_BASEADDR		0xf8f00100

/* System Timer Clock Frequency */
#define XILINX_PS7_CLOCK_FREQ	333333343

/* Uart console is ps7_uart_1 */
#define XILINX_PS7_UART
#define XILINX_PS7_UART_BASEADDR	0xe0001000
#define XILINX_PS7_UART_CLOCK_HZ	50000000

/* IIC doesn't exist */

/* GPIO doesn't exist */

/* SDIO controller is ps7_sd_0 */
#define XILINX_PS7_SDIO_BASEADDR		0xe0100000

/* Main Memory is ps7_ddr_0 */
#define XILINX_RAM_START	0x00000000
#define XILINX_RAM_SIZE		0x20000000

/* Flash Memory is ps7_qspi_0 */
#define XILINX_PS7_QSPI_FLASH_BASEADDR	0xE000D000
#define XILINX_SPI_FLASH_MAX_FREQ	50000000
#define XILINX_SPI_FLASH_CS	0

/* Sysace doesn't exist */

/* Ethernet controller is ps7_ethernet_0 */
#define XILINX_PS7_GEM_BASEADDR			0xe000b000
